"""PDF generation for certificates and passports (stub with reportlab structure)."""

from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch, cm
from reportlab.lib.colors import HexColor
import io


def generate_certificate_pdf(
    user_name: str,
    event_title: str,
    org_name: str,
    role: str,
    verification_code: str,
    issued_date: str,
) -> bytes:
    """Generate a certificate PDF and return raw bytes."""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=landscape(A4))
    width, height = landscape(A4)

    # Background
    c.setFillColor(HexColor("#0a0a0a"))
    c.rect(0, 0, width, height, fill=True)

    # Border
    c.setStrokeColor(HexColor("#00ffc2"))
    c.setLineWidth(3)
    c.rect(30, 30, width - 60, height - 60, stroke=True, fill=False)

    # Title
    c.setFillColor(HexColor("#00ffc2"))
    c.setFont("Helvetica-Bold", 36)
    c.drawCentredString(width / 2, height - 100, "CERTIFICATE OF PARTICIPATION")

    # Eventfy branding
    c.setFont("Helvetica", 14)
    c.setFillColor(HexColor("#666666"))
    c.drawCentredString(width / 2, height - 130, "EVENTFY — EVENT SUPER-APP")

    # Recipient
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica", 16)
    c.drawCentredString(width / 2, height - 180, "This certifies that")

    c.setFont("Helvetica-Bold", 28)
    c.setFillColor(HexColor("#00ffc2"))
    c.drawCentredString(width / 2, height - 220, user_name.upper())

    # Role
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica", 16)
    c.drawCentredString(width / 2, height - 260, f"participated as {role} in")

    # Event
    c.setFont("Helvetica-Bold", 22)
    c.setFillColor(HexColor("#ffd700"))
    c.drawCentredString(width / 2, height - 300, event_title)

    # Org
    c.setFillColor(HexColor("#cccccc"))
    c.setFont("Helvetica", 14)
    c.drawCentredString(width / 2, height - 330, f"Organized by {org_name}")

    # Date
    c.setFont("Helvetica", 12)
    c.setFillColor(HexColor("#888888"))
    c.drawCentredString(width / 2, height - 370, f"Issued on {issued_date}")

    # Verification
    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(HexColor("#00ffc2"))
    c.drawCentredString(width / 2, 60, f"Verification Code: {verification_code}")
    c.setFont("Helvetica", 9)
    c.setFillColor(HexColor("#666666"))
    c.drawCentredString(width / 2, 45, "Verify at eventfy.app/verify/" + verification_code)

    c.save()
    buffer.seek(0)
    return buffer.read()


def generate_passport_pdf(
    user_name: str,
    player_number: int,
    level: int,
    level_title: str,
    xp: int,
    events_attended: int,
    badges: list,
    skills: list,
) -> bytes:
    """Generate a player passport PDF and return raw bytes."""
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    # Background
    c.setFillColor(HexColor("#0a0a0a"))
    c.rect(0, 0, width, height, fill=True)

    # Header
    c.setFillColor(HexColor("#00ffc2"))
    c.setFont("Helvetica-Bold", 28)
    c.drawCentredString(width / 2, height - 60, "PLAYER PASSPORT")

    c.setFont("Helvetica", 12)
    c.setFillColor(HexColor("#666666"))
    c.drawCentredString(width / 2, height - 80, "EVENTFY — EVENT SUPER-APP")

    # Player info
    y = height - 130
    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica-Bold", 20)
    c.drawString(60, y, user_name.upper())

    y -= 30
    c.setFont("Helvetica", 14)
    c.setFillColor(HexColor("#00ffc2"))
    c.drawString(60, y, f"#{player_number}")
    c.setFillColor(HexColor("#ffd700"))
    c.drawString(200, y, f"Level {level} — {level_title}")

    y -= 25
    c.setFillColor(HexColor("#cccccc"))
    c.setFont("Helvetica", 12)
    c.drawString(60, y, f"Total XP: {xp:,}  |  Events Attended: {events_attended}")

    # Badges section
    y -= 50
    c.setFillColor(HexColor("#00ffc2"))
    c.setFont("Helvetica-Bold", 16)
    c.drawString(60, y, "BADGES")
    y -= 5

    c.setFillColor(HexColor("#ffffff"))
    c.setFont("Helvetica", 11)
    for badge in badges[:20]:
        y -= 20
        if y < 80:
            break
        c.drawString(80, y, f"🏅 {badge}")

    # Skills section
    if y > 150:
        y -= 35
        c.setFillColor(HexColor("#00ffc2"))
        c.setFont("Helvetica-Bold", 16)
        c.drawString(60, y, "SKILLS")
        y -= 5

        c.setFillColor(HexColor("#ffffff"))
        c.setFont("Helvetica", 11)
        for skill in skills[:15]:
            y -= 20
            if y < 80:
                break
            c.drawString(80, y, f"◆ {skill}")

    # Footer
    c.setFillColor(HexColor("#444444"))
    c.setFont("Helvetica", 9)
    c.drawCentredString(width / 2, 40, "Generated by Eventfy — eventfy.app")

    c.save()
    buffer.seek(0)
    return buffer.read()
